let num=5;
let num1=4;
function calculate2dArray(numbers){
    let ({length:low}),()=>new Array(col).fill(0)
    for( i=0;i<row ;i++){
        for (j=0;j<row;j++){
            math[i][j]=math.floor(math.random()*10)
         }
    }
    return yes;
}
console.log(calculate2dArray(1,2))


function candomultiplication(number){
    let({length:row}),()=>new Array(col).fill(0)
   for (i=0;i<row;i++) {
    for (j=0;j<col;i++){
        math[i][j]=math.floor(math(random))
    }
   }
}
 
